"""phase4_time_off

Revision ID: 202e969ce549
Revises: a178d4185523
Create Date: 2026-09-05 16:21:53.349382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202e969ce549'
down_revision: Union[str, Sequence[str], None] = 'a178d4185523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_off_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('unit', sa.Enum('DAYS', 'HOURS', name='timeoffunit'), nullable=False),
    sa.Column('requires_allocation', sa.Boolean(), nullable=False),
    sa.Column('approval_policy', sa.Enum('NONE', 'MANAGER', 'HR', name='approvalpolicy'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_color', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_time_off_types_id'), ['id'], unique=False)

    op.create_table('time_off_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'TO_APPROVE', 'APPROVED', 'REFUSED', name='allocationstatus'), nullable=False),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_allocations_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_allocations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_allocations_time_off_type_id'), ['time_off_type_id'], unique=False)

    op.create_table('time_off_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('time_off_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('TO_APPROVE', 'APPROVED', 'REFUSED', name='requeststatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['time_off_allocations.id'], ),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['time_off_type_id'], ['time_off_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_off_requests_time_off_type_id'), ['time_off_type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_requests_time_off_type_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_requests_employee_id'))

    op.drop_table('time_off_requests')
    with op.batch_alter_table('time_off_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_allocations_time_off_type_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_allocations_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_allocations_employee_id'))

    op.drop_table('time_off_allocations')
    with op.batch_alter_table('time_off_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_off_types_id'))
        batch_op.drop_index(batch_op.f('ix_time_off_types_code'))

    op.drop_table('time_off_types')
    # ### end Alembic commands ###
