"""phase5_payroll

Revision ID: 263963d3918b
Revises: 202e969ce549
Create Date: 2026-09-05 16:45:36.429753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263963d3918b'
down_revision: Union[str, Sequence[str], None] = '202e969ce549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_structures_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_salary_structures_id'), ['id'], unique=False)

    op.create_table('salary_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('BASIC', 'ALLOWANCE', 'GROSS', 'DEDUCTION', 'NET', name='rulecategory'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('computation_method', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', name='computationmethod'), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('percentage_base', sa.String(), nullable=True),
    sa.Column('formula_expression', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salary_structure_id', 'code', name='uq_salary_rule_structure_code')
    )
    with op.batch_alter_table('salary_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_rules_salary_structure_id'), ['salary_structure_id'], unique=False)

    op.create_table('payruns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', name='payrunstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payruns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payruns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payruns_reference'), ['reference'], unique=True)

    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payrun_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('salary_structure_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', name='payrunstatus'), nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expected_work_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('worked_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('basic', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payrun_id', 'employee_id', name='uq_payslip_payrun_employee')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_payrun_id'), ['payrun_id'], unique=False)

    op.create_table('payroll_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKER', 'WARNING', 'INFO', name='warningseverity'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_warnings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_warnings_payslip_id'), ['payslip_id'], unique=False)

    op.create_table('payslip_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('salary_rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_name_snapshot', sa.String(), nullable=False),
    sa.Column('rule_code_snapshot', sa.String(), nullable=False),
    sa.Column('category_snapshot', sa.Enum('BASIC', 'ALLOWANCE', 'GROSS', 'DEDUCTION', 'NET', name='rulecategory'), nullable=False),
    sa.Column('sequence_snapshot', sa.Integer(), nullable=False),
    sa.Column('computation_method_snapshot', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', name='computationmethod'), nullable=False),
    sa.Column('base_description_snapshot', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.ForeignKeyConstraint(['salary_rule_id'], ['salary_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payslip_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslip_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslip_lines_payslip_id'), ['payslip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslip_lines_payslip_id'))
        batch_op.drop_index(batch_op.f('ix_payslip_lines_id'))

    op.drop_table('payslip_lines')
    with op.batch_alter_table('payroll_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_warnings_payslip_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_warnings_id'))

    op.drop_table('payroll_warnings')
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_payrun_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_employee_id'))

    op.drop_table('payslips')
    with op.batch_alter_table('payruns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payruns_reference'))
        batch_op.drop_index(batch_op.f('ix_payruns_id'))

    op.drop_table('payruns')
    with op.batch_alter_table('salary_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_rules_salary_structure_id'))
        batch_op.drop_index(batch_op.f('ix_salary_rules_id'))

    op.drop_table('salary_rules')
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_structures_id'))
        batch_op.drop_index(batch_op.f('ix_salary_structures_code'))

    op.drop_table('salary_structures')
    # ### end Alembic commands ###
