"""phase3 attendance

Revision ID: a178d4185523
Revises: e8ac28b2eaef
Create Date: 2026-09-05 15:52:45.865095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a178d4185523'
down_revision: Union[str, Sequence[str], None] = 'e8ac28b2eaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_attendance_date'))

    op.drop_table('attendances')
    # ### end Alembic commands ###
