"""phase2 employee contract working schedule

Revision ID: e8ac28b2eaef
Revises: 418d8c655fed
Create Date: 2026-09-05 14:44:02.166207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ac28b2eaef'
down_revision: Union[str, Sequence[str], None] = '418d8c655fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    employee_status = sa.Enum('ACTIVE', 'INACTIVE', name='employeestatus')
    employee_status.create(op.get_bind(), checkfirst=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('job_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('job_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_positions_id'), ['id'], unique=False)

    op.create_table('working_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='schedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('working_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_schedules_id'), ['id'], unique=False)

    op.create_table('working_schedule_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working_schedule_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('working_schedule_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_schedule_lines_id'), ['id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=False),
    sa.Column('working_schedule_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('wage_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('salary_structure_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ),
    sa.ForeignKeyConstraint(['working_schedule_id'], ['working_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_reference'), ['reference'], unique=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('work_location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', employee_status, nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_position_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('working_schedule_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)
        batch_op.create_foreign_key('fk_employees_manager_id_employees', 'employees', ['manager_id'], ['id'])
        batch_op.create_foreign_key('fk_employees_job_position_id_job_positions', 'job_positions', ['job_position_id'], ['id'])
        batch_op.create_foreign_key('fk_employees_department_id_departments', 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_employees_working_schedule_id_working_schedules', 'working_schedules', ['working_schedule_id'], ['id'])
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_employees_manager_id_employees', type_='foreignkey')
        batch_op.drop_constraint('fk_employees_job_position_id_job_positions', type_='foreignkey')
        batch_op.drop_constraint('fk_employees_department_id_departments', type_='foreignkey')
        batch_op.drop_constraint('fk_employees_working_schedule_id_working_schedules', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_column('working_schedule_id')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('job_position_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('status')
        batch_op.drop_column('work_location')
        batch_op.drop_column('employee_code')

    sa.Enum('ACTIVE', 'INACTIVE', name='employeestatus').drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_reference'))
        batch_op.drop_index(batch_op.f('ix_contracts_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('working_schedule_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_working_schedule_lines_id'))

    op.drop_table('working_schedule_lines')
    with op.batch_alter_table('working_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_working_schedules_id'))

    op.drop_table('working_schedules')
    with op.batch_alter_table('job_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_positions_id'))

    op.drop_table('job_positions')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###
