"""phase7 paytrace snapshot fields

Revision ID: ea2fc0bd7980
Revises: 8e682f94c55d
Create Date: 2026-09-06 00:52:53.621229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2fc0bd7980'
down_revision: Union[str, Sequence[str], None] = '8e682f94c55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_amount_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('percentage_snapshot', sa.Numeric(precision=6, scale=2), nullable=True))
        batch_op.add_column(sa.Column('base_code_snapshot', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('base_amount_snapshot', sa.Numeric(precision=14, scale=4), nullable=True))
        batch_op.add_column(sa.Column('formula_inputs_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip_lines', schema=None) as batch_op:
        batch_op.drop_column('formula_inputs_snapshot')
        batch_op.drop_column('base_amount_snapshot')
        batch_op.drop_column('base_code_snapshot')
        batch_op.drop_column('percentage_snapshot')
        batch_op.drop_column('fixed_amount_snapshot')

    # ### end Alembic commands ###
